#!/bin/bash

NOMINATIM_PASSWORD="${NOMINATIM_PASSWORD:-$PGPASSWORD}"
NOMINATIM_DATABASE_DSN="${NOMINATIM_DATABASE_DSN:-host=$PGHOST dbname=$PGDATABASE user=$PGUSER password=$PGPASSWORD}"

CONFIG_FILE="${PROJECT_DIR}/.env"
CONFIG_TEMPLATE="/app/env.template"

apply_config() {
  cp "$CONFIG_TEMPLATE" "$CONFIG_FILE"

  sed -i "s|__NOMINATIM_DATABASE_DSN__|$NOMINATIM_DATABASE_DSN|g" "$CONFIG_FILE"

  if [ "$REPLICATION_URL" != "" ]; then
    sed -i "s|__REPLICATION_URL__|$REPLICATION_URL|g" "$CONFIG_FILE"
    if [[ "$REPLICATION_UPDATE_INTERVAL" =~ ^[0-9]+$ ]]; then
      sed -i "s/NOMINATIM_REPLICATION_UPDATE_INTERVAL=86400/NOMINATIM_REPLICATION_UPDATE_INTERVAL=$REPLICATION_UPDATE_INTERVAL/g" "$CONFIG_FILE"
    fi
    if [[ "$REPLICATION_RECHECK_INTERVAL" =~ ^[0-9]+$ ]]; then
      sed -i "s/NOMINATIM_REPLICATION_RECHECK_INTERVAL=900/NOMINATIM_REPLICATION_RECHECK_INTERVAL=$REPLICATION_RECHECK_INTERVAL/g" "$CONFIG_FILE"
    fi
  fi

  if [ ! -z "$IMPORT_STYLE" ]; then
    sed -i "s|__IMPORT_STYLE__|${IMPORT_STYLE}|g" "$CONFIG_FILE"
  else
    sed -i "s|__IMPORT_STYLE__|full|g" "$CONFIG_FILE"
  fi

  if [ -d "${PROJECT_DIR}/flatnode" ]; then
    sed -i 's|^NOMINATIM_FLATNODE_FILE=$|NOMINATIM_FLATNODE_FILE="'"${PROJECT_DIR}"'/flatnode/flatnode.file"|g' "$CONFIG_FILE"
  fi

  if [ "$IMPORT_TIGER_ADDRESSES" = "true" ] || [ -f "$IMPORT_TIGER_ADDRESSES" ]; then
    echo NOMINATIM_USE_US_TIGER_DATA=yes >> "$CONFIG_FILE"
  fi
}
