# Connectivity
max_connections = 100
listen_addresses = '*'

# change these based on the specifications of your system
# the recommended nominatim values: https://nominatim.org/release-docs/latest/admin/Installation/#tuning-the-postgresql-database

# shared_buffers = 2GB
# effective_cache_size = 24GB
# work_mem = 50MB
# maintenance_work_mem = 10GB
# autovacuum_work_mem = 2GB

# wal_level = replica
# max_wal_senders = 10
# max_wal_size = 1GB

# checkpoint_timeout = 10min
# checkpoint_completion_target = 0.9

# max_parallel_workers_per_gather = 4
# max_parallel_workers = 16

# synchronous_commit = off
random_page_cost = 1.1

# PgHero Requirements
# shared_preload_libraries = 'pg_stat_statements'
# pg_stat_statements.track = all
# track_io_timing = on

# !IMPORTANT!
# add these to your postgres conf for import only
# remove them after import and restart the database
fsync = off
full_page_writes = off
