#! /usr/bin/env python3

# This script sends a HTTP request to a URL and asserts that its JSON
# response contains a non-empty array.
#
# It retries the HTTP request a number of times.

import logging
import requests
import sys
import json

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

logging.basicConfig(level=logging.WARNING)

s = requests.Session()
retries = Retry(total=7, backoff_factor=2, status_forcelist=[ 502, 503, 504 ])
s.mount('http://', HTTPAdapter(max_retries=retries))

resp = s.get(sys.argv[1])

if(resp.status_code != 200):
    print(f'Endpoint returned status code {resp.status_code}: {resp.content}')
    sys.exit(1)

else:
    jsn = resp.json()
    print(f"JSON response returned by {sys.argv[1]}:")
    print(json.dumps(jsn, indent = 2))
    assert len(jsn) > 0
    print("✅ JSON was non-empty array")

