#! /usr/bin/env python3

# This script sends a HTTP request to a URL and asserts that its
# response matches that of an instance running in reverse-only mode.
#
# It retries the HTTP request a number of times.

import logging
import requests
import sys
import json

from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

logging.basicConfig(level=logging.WARNING)

s = requests.Session()
retries = Retry(total=18, backoff_factor=2, status_forcelist=[502, 503, 504])
s.mount('http://', HTTPAdapter(max_retries=retries))

resp = s.get(sys.argv[1])
jsn = resp.json()

if (resp.status_code == 404 and jsn["error"]["message"] == "Reverse-only import does not support forward searching."):
    print("✅ Nominatim is running in reverse-only mode")
else:
    print(f'Endpoint returned status code {resp.status_code}: {resp.content}')
    sys.exit(1)