name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build docker image

    runs-on: ubuntu-latest
    outputs:
      NOMINATIM_VERSION: ${{ steps.get_version.outputs.NOMINATIM_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Nominatim Version
        id: get_version
        run: echo "NOMINATIM_VERSION=$(grep -oP '(?<=ARG NOMINATIM_VERSION=)[0-9.]+' Dockerfile)" >> $GITHUB_OUTPUT

      - name: Build and export image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ github.repository_owner }}/nominatim:${{ steps.get_version.outputs.NOMINATIM_VERSION }}
